chore: update project templates
Hapag-Lloyd/terraform-aws-bastion-host-ssm pull request #313
Opened 2024-05-23 13:49 UTC by kayman-mk

This PR updates the project templates.

2024-05-23 13:53 UTC, kayman-mk commented
We can go with the failing pipeline. This will be fixed by using the new workflow files.

2024-05-23 19:26 UTC, PascalFrenz requested changes

2024-05-23 19:26 UTC, PascalFrenz commented on .github/update_templates.sh
> +gh repo clone https://github.com/Hapag-Lloyd/Repository-Template-Maven.git "$latest_template_path"
This references the wrong repo. Should be https://github.com/Hapag-Lloyd/Repository-Template-Terraform-Module, right?

2024-06-06 21:06 UTC, PascalFrenz approved these changes

2024-08-10 22:08 UTC, PascalFrenz commented
@kayman-mk can these changes be merged?

2024-08-20 11:39 UTC, merged

2024-08-21 06:12 UTC, HapagLloydTechnicalUser commented
:tada: This issue has been resolved in version 3.0.1 :tada:

The release is available on [GitHub release](https://github.com/Hapag-Lloyd/terraform-aws-bastion-host-ssm/releases/tag/3.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: